#!/bin/bash

YELLOW='\033[1;33m'
NC='\033[0m' # No Color
OS=`uname -o`

copy()
{
        if [ $1 -ot $2 ]; then
                printf "Skip copying [${YELLOW}$1${NC}] -> [${YELLOW}$2${NC}]\n"
                return
        fi

        printf "Copying [${YELLOW}$1${NC}] -> [${YELLOW}$2${NC}]\n"
        cp -f $1 $2
}

main()
{
	clear
	read -p "Press [Enter] key to install files into HOME directory at ..."

	if [ -z "$HOME" ]; then
        	printf "Install failed: ${YELLOW}\$HOME${NC} environment variable not set.\n"
        	exit 1
	fi

	if [ ! -d "$HOME" ]; then
		printf "Install failed: [${YELLOW}$HOME${NC}] folder was not found.\n"
		exit 1
	fi

	cat config > .gitconfig
	if [ "${OS}" == "GNU/Linux" ]; then
		printf "Customizing Linux configuration . . . \n"
		cat config.lin >> .gitconfig
	else
		printf "Customizing MSys configuration . . . \n"
		cat config.win >> .gitconfig
	fi

	if [ -s config.secure ]; then
		printf "Ammending secure local only settings . . .\n"
		cat config.secure >> .gitconfig
	fi

	copy .gitconfig "$HOME/.gitconfig"
	rm .gitconfig

	copy .gitattributes "$HOME/.gitattributes"
}

main
